server:
  port: 8888

spring:
  config:
    import: "optional:configserver:"

  application:
    name: application
  cloud:
    config:
      server:
        git:
          uri: https://github.com/HyeonGiMin/wimp-config-repo
          username: HyeonGi Min
          password: ${GITHUB_TOKEN}